# ─────────────────────────────────────────────────────────────
#  Pedidos360 — nginx del contenedor del front.
#  Sirve el SPA (dist/.../browser) y hace de API Gateway: enruta /api/*
#  al servicio que corresponda por nombre de red de docker-compose.
# ─────────────────────────────────────────────────────────────

upstream auth_backend      { server auth:8080; }
upstream inventory_backend { server inventory:8083; }
upstream orders_backend    { server orders:8081; }

server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/auth/ {
    proxy_pass http://auth_backend;
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location = /api/me {
    proxy_pass http://auth_backend;
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # --- Administracion de roles: /api/admin/* ---
  location /api/admin/ {
    proxy_pass http://auth_backend;
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/inventory/ {
    proxy_pass http://inventory_backend;
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/orders/ {
    proxy_pass http://orders_backend;
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/ { return 404; }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
